# These are supported funding model platforms

bitcoin: bc1qgfrpxmvgfpmhrqdgcat5rnd07qcz36hxm38emq

Ethereum: 0xd5da635AcDB5E5e31A814D4BF437415DD6A520e1

Cardano: addr1qynngrngf9lfr6mpvn47fq55fesgztcsm5p0k2x8g4h9g3fg9t38qdhl0tp84g0uqtgsxmxd0nx5y9yjxvzp0ufuc8dsjgapsg
